Repository Tit0u4N/games-on-web-team-ficsit, pull requests merged in 2024-05, with the labels that each got.

#121 Fix/120 fix images path
  public/character_1.png
  public/character_2.png
  public/character_3.png
  public/images/characters/index.ts
  public/images/menu/avatar_bapt.png
  public/images/menu/avatar_tamas.png
  public/images/menu/avatar_titou.jpg
  public/images/menu/bg.png
  src/modules/gamecore/view/React/ConfigureCharacters.tsx
  src/modules/gamecore/view/React/MenuView.tsx
  src/modules/gamecore/view/React/SpeechBox.tsx
  src/modules/inventory/view/React/InventoryLayout.tsx
  src/plugins/tailwind.config.js
Labels: enhancement

#123 Dev
  package.json
  public/character_1.png
  public/character_2.png
  public/character_3.png
  public/images/building/signal-cellular-1.svg
  public/images/building/signal-cellular-2.svg
  public/images/building/signal-cellular-3.svg
  public/images/characters/index.ts
  public/images/menu/avatar_bapt.png
  public/images/menu/avatar_tamas.png
  public/images/menu/avatar_titou.jpg
  public/images/menu/bg.png
  public/images/narrator/narrator.png
  src/component/options/ControlOption.tsx
  src/component/options/ControlOptions.tsx
  src/core/Interfaces.ts
  src/core/config.json
  src/modules/audio/view/React/AudioComponent.tsx
  src/modules/audio/view/React/AudioModal.tsx
  src/modules/building/view/React/trainingCenter/CharacterStats.tsx
  src/modules/building/view/React/trainingCenter/ClickableCard.tsx
  src/modules/building/view/React/trainingCenter/wired-outline-153-bar-chart.json
  src/modules/character/BuilderFactory/CharacterFactory.ts
  src/modules/character/model/Character.ts
  src/modules/character/presenter/CharacterPresenter.ts
  src/modules/character/view/Babylon/CharacterView.ts
  src/modules/character/view/Babylon/PawnView.ts
  src/modules/character/view/React/CharacterLayout.tsx
  src/modules/character/view/React/GameCharacterLayout.tsx
  src/modules/dice/presenter/DicePresenter.ts
  src/modules/dice/view/Babylon/Dice3D.ts
  src/modules/event/view/React/EventLayout.tsx
  src/modules/event/view/React/RulesLayout.tsx
  src/modules/gamecore/presenter/GameCorePresenter.ts
  src/modules/gamecore/view/React/ConfigureCharacters.tsx
  src/modules/gamecore/view/React/GameSettingsComponent.tsx
  src/modules/gamecore/view/React/GameView.tsx
  src/modules/gamecore/view/React/MenuView.tsx
  src/modules/gamecore/view/React/RoundStatusBar.tsx
  src/modules/gamecore/view/React/SpeechBox.tsx
  src/modules/inventory/view/React/InventoryLayout.tsx
  src/modules/map/core/Noise.ts
  src/modules/map/view/Babylon/TileView.ts
  src/modules/tournament/model/TournamentModel.ts
  src/modules/tournament/view/React/NPC.tsx
  src/modules/tournament/view/React/TournamentView.tsx
  src/plugins/tailwind.config.js
Labels: enhancement

#124 fix: removing dice in tournament
  src/modules/tournament/view/React/TournamentView.tsx
Labels: bug

#126 Feature/125 favicon
  index.html
  public/images/ico.png
  public/images/op-image.png
Labels: enhancement

#122 Feature/100 final tournament
  package.json
  src/component/options/ControlOptions.tsx
  src/core/Interfaces.ts
  src/modules/building/model/ArenaModel.ts
  src/modules/building/model/BuildingFactory.ts
  src/modules/building/model/TrainingCenterModel.ts
  src/modules/building/view/React/trainingCenter/CharacterStats.tsx
  src/modules/character/BuilderFactory/CharacterFactory.ts
  src/modules/character/presenter/CharacterPresenter.ts
  src/modules/character/view/React/CharacterLayout.tsx
  src/modules/character/view/React/GameCharacterLayout.tsx
  src/modules/dice/view/Babylon/Dice3D.ts
  src/modules/event/view/React/RulesLayout.tsx
  src/modules/gamecore/presenter/ApplicationStatus.ts
  src/modules/gamecore/presenter/GameCorePresenter.ts
  src/modules/gamecore/view/React/ConfigureCharacters.tsx
  src/modules/gamecore/view/React/GameSettingsComponent.tsx
  src/modules/gamecore/view/React/GameView.tsx
  src/modules/gamecore/view/React/MainView.tsx
  src/modules/gamecore/view/React/MenuView.tsx
  src/modules/gamecore/view/React/OlympicsView.tsx
  src/modules/gamecore/view/React/RoundStatusBar.tsx
  src/modules/gamecore/view/React/SpeechBox.tsx
  src/modules/inventory/view/React/InventoryLayout.tsx
  src/modules/map/view/Babylon/TileView.ts
  src/modules/olympics/model/OlympicsModel.ts
  src/modules/olympics/presenter/OlympicsPresenter.ts
  src/modules/olympics/view/React/OlympicsTournamentView.tsx
  src/modules/olympics/view/React/PersonalStanding.tsx
  src/modules/olympics/view/React/StandingView.tsx
  src/modules/olympics/view/React/TeamStanding.tsx
  src/modules/olympics/view/React/TeamView.tsx
  src/modules/tournament/model/TournamentDifficulty.ts
  src/modules/tournament/model/TournamentFactory.ts
  src/modules/tournament/model/TournamentModel.ts
  src/modules/tournament/presenter/TournamentManagerPresenter.ts
  src/modules/tournament/view/React/TournamentEndView.tsx
Labels: enhancement

#131 Deployment with new features
  src/core/Interfaces.ts
  src/core/config.json
  src/modules/audio/view/React/MusicView.tsx
  src/modules/character/view/React/CharacterLayout.tsx
  src/modules/event/view/React/RulesLayout.tsx
  src/modules/gamecore/presenter/GameCorePresenter.ts
  src/modules/gamecore/view/React/GameView.tsx
  src/modules/gamecore/view/React/SpeechBox.tsx
  src/modules/gamecore/view/React/narrator/IntroductionSpeech.tsx
  src/modules/gamecore/view/React/narrator/SimpleMessageSpeechBox.tsx
  src/modules/gamecore/view/React/narrator/SpeechBox.tsx
  src/modules/gamecore/view/React/narrator/TutorialControlsSpeech.tsx
  src/modules/olympics/presenter/OlympicsPresenter.ts
Labels: enhancement

#132 Another one minor feature
  src/core/Interfaces.ts
  src/core/config.json
  src/modules/event/view/React/RulesLayout.tsx
  src/modules/gamecore/view/React/GameView.tsx
  src/modules/gamecore/view/React/MenuView.tsx
  src/modules/map/presenter/MapPresenter.ts
Labels: enhancement

#133 fix: svg bar choices cards path #00
  src/core/Interfaces.ts
  src/core/config.json
  src/modules/audio/view/React/MusicView.tsx
  src/modules/character/view/React/CharacterLayout.tsx
  src/modules/gamecore/view/React/GameView.tsx
  src/modules/gamecore/view/React/MenuView.tsx
  src/modules/gamecore/view/React/narrator/IntroductionSpeech.tsx
  src/modules/gamecore/view/React/narrator/SimpleMessageSpeechBox.tsx
  src/modules/gamecore/view/React/narrator/SpeechBox.tsx
  src/modules/gamecore/view/React/narrator/TutorialControlsSpeech.tsx
Labels: enhancement

#134 Last release
  src/core/config.json
  src/modules/gamecore/view/React/RoundStatusBar.tsx
Labels: documentation, enhancement
